# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RegDB.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 171)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 20, 56, 12))
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(90, 20, 171, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(20, 50, 56, 12))
        self.label_2.setObjectName("label_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_2.setGeometry(QtCore.QRect(90, 50, 171, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_3.setGeometry(QtCore.QRect(90, 80, 171, 20))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(20, 80, 56, 12))
        self.label_3.setObjectName("label_3")

        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(290, 20, 91, 31))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(290, 70, 91, 31))
        self.pushButton_2.setObjectName("pushButton_2")

        self.lineEdit_4 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_4.setGeometry(QtCore.QRect(90, 101, 171, 20))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(30, 140, 341, 16))
        self.label_5.setObjectName("label_5")


        
        self.lineEdit_3.setEchoMode(QtWidgets.QLineEdit.Password) ## password
        self.lineEdit_4.setEchoMode(QtWidgets.QLineEdit.Password) ## password

        self.pushButton_2.clicked.connect(Dialog.close)

        self.filename = "materialdb.dat"
        try: 
            with open(self.filename) as DB:
                lines=DB.readlines()
            self.lineEdit.setText(lines[0].strip())
            # self.lineEdit_2.setText(lines[1].strip())
            # self.lineEdit_3.setText(lines[2].strip())
        except:
            f = open(self.filename, 'w')
            ip = '10.82.66.65'
            f.write(ip+"\n")
            id = 'h20200155'
            f.write(id+"\n")
            pw = 'h20200155'
            f.write(pw+"\n")
            f.close()

        self.retranslateUi(Dialog)
        self.pushButton.clicked.connect(self.SaveDB)

        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Registering to Material DB"))
        self.label.setText(_translate("Dialog", "Server IP"))
        self.label_2.setText(_translate("Dialog", "User"))
        self.label_3.setText(_translate("Dialog", "PW"))
        self.pushButton.setText(_translate("Dialog", "Save"))
        self.pushButton_2.setText(_translate("Dialog", "Exit"))
        self.label_5.setText(_translate("Dialog", "Hosts RND 10.82.66.65, ATC 10.1.1.22:3001, CTC 202.31.116.35:3001, ETC 192.168.202.4:3001"))


    def SaveDB(self): 
        ip = self.lineEdit.text().strip()
        id = self.lineEdit_2.text().strip()
        pw = self.lineEdit_3.text().strip()
        pw1 = self.lineEdit_4.text().strip()
        if pw1 == pw: 
            f = open(self.filename, 'w')
            f.write(ip+"\n")
            f.write(id+"\n")
            f.write(pw+"\n")
            f.close()
            self.label_5.setText("Saved well!!")
        else: 
            self.label_5.setText("Passwords are not the same!!")

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
